### ISSUE TITLE
Github API Deprecated

### ISSUE THREAD

**Issue by xeddmc** [kamranahmedse/githunt#45]
The Github API used is deprecated. Any idea when an update will be rolled out? As it is now, every time a tab is opened, Github sends out an email telling us the API is deprecated. Quite annoying ><

**Comment by kamranahmedse** [comment]
Thank you for reporting. This has been fixed and deployed 🙏

**Comment by dnebing** [comment]
I have 3.9 and I'm still getting these emails about the deprecated API...

**Comment by kamranahmedse** [comment]
It's been in pending review. I am not sure how long it is going to take. I have reached out to the team, let's see how it goes. For the time being, keep ignoring the emails or [use the website](https://kamranahmed.info/githunt) :) 

![image](https://user-images.githubusercontent.com/4921183/74575322-fd857e00-4f9f-11ea-97a3-61c4e8fc9a8b.png)
